#!/usr/bin/env python3
"""Generate integration ID vocabularies and glossary rows from canonical CSVs."""
import argparse
import csv
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(name):
    with (ROOT / name).open(newline="", encoding="utf-8") as source:
        return list(csv.DictReader(source))


def outputs():
    objects = read("itoms_objects.csv")
    relationships = read("itoms_relationships.csv")
    registry = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://schemas.itoms.invalid/contracts/canonical-ids.schema.json",
        "$comment": "Generated by scripts/generate-contract-registry.py. Edit root registries, never this file.",
        "$defs": {
            "ObjectID": {"type": "string", "enum": [o["ObjectID"] for o in objects]},
            "RelationshipID": {"type": "string", "enum": [r["RelationshipID"] for r in relationships]},
        },
    }
    table = '<section id="objects" class="panel"><h2>Canonical Object Register</h2><p>Generated from itoms_objects.csv. Proposed entries require ADR-0010 review.</p><table class="grid"><tr><th>Object ID</th><th>Name</th><th>Domain</th><th>Definition</th><th>Status</th></tr>\n'
    for obj in objects:
        table += "<tr>" + "".join("<td>" + html.escape(obj[key]) + "</td>" for key in ("ObjectID", "ObjectName", "DomainTag", "Definition", "Status")) + "</tr>\n"
    table += "</table></section>\n"
    glossary = (ROOT / "itoms_glossary.html").read_text()
    start, end = glossary.index('<section id="objects"'), glossary.index('<section id="forms"')
    return {
        ROOT / "contracts/canonical-ids.schema.json": json.dumps(registry, indent=2) + "\n",
        ROOT / "itoms_glossary.html": glossary[:start] + table + glossary[end:],
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit("Generated canonical projections differ: " + ", ".join(stale))
    print("Canonical ID and glossary projections are current.")
